homebrew_taps:
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - homebrew/core
  - homebrew/services
homebrew_packages:
  - name: ansible
  - name: aria2
  - name: arp-scan
  - name: clang-format
  - name: cloudflared
  - name: gcc
  - name: gh
  - name: git
  - name: gping
  - name: gtop
  - name: htop
  - name: mas
  - name: neofetch
  - name: neovim
  - name: netcat
  - name: nmap
  - name: node # this is need to use yarn
  - name: openvpn
  - name: python
  - name: python-tk
  - name: python-tk@3.11
  - name: qemu
  - name: rust-analyzer
  - name: rustscan
  - name: rustup
  - name: starship
  - name: telnet
  - name: tmux
  - name: tor
  - name: tree
  - name: wget
  - name: wireguard-tools
  - name: yarn
  - name: z
  - name: zplug
homebrew_cask_packages:
  - name: alacritty
  - name: burp-suite
  - name: clipy
  - name: discord
  - name: drawio
  - name: firefox
  - name: font-hack-nerd-font
  - name: font-moslo-lg
  - name: ghidra
  - name: gns3
  - name: google-chrome
  - name: hammerspoon
  - name: hex-fiend
  - name: macfuse
  - name: mactex-no-gui
  - name: microsoft-office
  - name: microsoft-teams
  - name: notion
  - name: obsidian
  - name: orbstack
  - name: owasp-zap
  - name: postman
  - name: raspberry-pi-imager
  - name: save-hollywood
  - name: slack
  - name: tor-browser
  - name: utm
  - name: visual-studio-code
  - name: wireshark
  - name: zap
  - name: zoom
apple_store_packages:
  - id: 1193539993 # Brother iPrint&Scan
  - id: 405399194 # Kindle
  - id: 539883307 # LINE
  - id: 1295203466 # Microsoft Remote Desktop
  - id: 1475387142 # Tailscale
  - id: 1451685025 # Wireguard
clones:
  - url: https://github.com/tmux-plugins/tpm
    path: ~/.tmux/plugins/tpm
dotfiles:
  - .config
  - .gitignore
  - .latexmkrc
  - .tmux.conf
  - .vimrc
  - .zprofile
  - .zshrc
  - .hammerspoon
code_extensions:
  - atlassian.atlascode
  - DavidAnson.vscode-markdownlint
  - James-Yu.latex-workshop
  - mhutchie.git-graph
  - ms-azuretools.vscode-docker
  - MS-CEINTL.vscode-language-pack-ja
  - ms-python.isort
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-toolsai.jupyter
  - ms-toolsai.jupyter-keymap
  - ms-toolsai.jupyter-renderers
  - ms-toolsai.vscode-jupyter-cell-tags
  - ms-toolsai.vscode-jupyter-slideshow
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode.remote-explorer
  - oderwat.indent-rainbow
  - redhat.ansible
  - redhat.vscode-yaml
  - rust-lang.rust-analyzer
  - shardulm94.trailing-spaces
  - techer.open-in-browser
  - usernamehw.errorlens
  - vscodevim.vim
  - yzhang.markdown-all-in-one
python_modules:
  - name: matplotlib
  - name: numpy
  - name: pandas
  - name: pip
  - name: pytest
  - name: scapy
yarn_packages:
  - name: chokidar-cli
