- block:
    - name: checkout dotfiles
      ansible.builtin.git:
        repo: https://github.com/nyahahanoha/dotfiles_for_mac
        dest: ~/dotfiles/
        remote: main
        force: yes

    - name: create symlinks
      ansible.builtin.file:
        src: ~/dotfiles/{{ item }}
        dest: ~/{{ item }}
        state: link
        force: yes
      with_items: "{{ dotfiles }}"

  tags:
    - dotfiles
