- block:
    - name: apple store packages upgrede
      community.general.mas:
        upgrade_all: true

    - name: apple store packages install
      community.general.mas:
        id: "{{ item.id }}"
        state: '{{ item.state | default("present") }}'
      with_items: "{{ apple_store_packages }}"

  tags:
    - mas
