- block:
    - name: homebrew cask packages install
      community.general.homebrew_cask:
        name: "{{ item.name }}"
        state: '{{ item.state | default("present") }}'
        upgrade_all: true
      with_items: "{{ homebrew_cask_packages }}"

  tags:
    - homebrew_cask
